#!/bin/sh
export PROJECT_ID="INSERT YOUR PROJECT ID HERE"
export OAUTH2_CLIENT_ID="INSERT YOUR OAUTH2 CREDENTIALS CLIENT ID HERE"
export OAUTH2_CLIENT_SECRET="INSERT YOUR OAUTH2 CREDENTIALS CLIENT SECRET HERE"
